accounts/urls.py
from django.contrib.auth import views as auth_views
from .views import UserListView, UserDetailView,UserCreateView,UserUpdateView,CustomLoginView,UserRegistrationView
from django.urls import path
from . import views, profile_views

from django.urls import path
#from .views import CustomLogoutView
from .views import confirm_logout



urlpatterns = [

    path('login/', CustomLoginView.as_view(), name='login'),
    #path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('user/password/reset/<int:user_id>/', views.reset_password, name='admin_reset_password'),
    path('user/password/reset/', profile_views.reset_password, name='user_reset_password'),
    path('profile/', views.profile, name='profile'),
    path('list/', UserListView.as_view(), name='user_list'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('add/', UserCreateView.as_view(), name='user-create'),
    path('details/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'),
         name='password_reset'),
    path('password-reset-done/',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
    path('logout/', views.logout_view, name='logout'),
    #path('confirm-logout/', confirm_logout, name='confirm_logout'),
    path('confirm-logout/', confirm_logout, name='confirm_logout'),

]

points/urls.py
from django.urls import path,include

from .import views

#app_name = 'points'

urlpatterns = [
    #email and sms Templates
    path('templates/', views.list_templates, name='template_list'),
    path('templates/edit/<int:pk>/', views.edit_template, name='edit_template'),
    path('templates/add/multimedia', views.add_template, name='template_add'),
    path('templates/sms/add', views.add_template_sms, name='template_sms_add'),
    path('templates/preview/<int:pk>/', views.preview_template, name='preview_template'),
    #dashboards
    path('bonus/report/', views.bonus_report, name='bonus_report'),
    path('top/contributors/', views.top_contributors, name='top_contributors'),
    path('dashboard/', views.unified_dashboard, name='dashboard'),

]

tra_ratings/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include
from django.views.generic import TemplateView
from tra_theme.views import ManifestView


def custom_404(request, exception):
    return render(request, "errors/404.html", status=404)


def custom_500(request):
    return render(request, "errors/500.html", status=500)


def custom_403(request, exception):
    return render(request, "errors/403.html", status=403)


handler404 = custom_404
handler500 = custom_500
handler403 = custom_403

path('manifest.json', ManifestView.as_view(), name='manifest'),


urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('rating.urls')),
                  path('accounts/', include('accounts.urls')),
                  path('api/v1/', include('ext_conn.urls')),
                  path('notification/', include('sms_app.urls')),
                  path('points/', include('points.urls')),
                  path('ckeditor5/', include('django_ckeditor_5.urls')),
                  path('mobile/', include('tra_theme.urls')),
                  path('service-worker.js', TemplateView.as_view(template_name="tra_ratings/service-worker.js", content_type="application/javascript"),
                       name='service-worker.js'),
                  path('photo/rating/', include('plate_ocr.urls')),
                  path('offline/', TemplateView.as_view(template_name="tra_ratings/offline.html"), name='offline'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordResetForm
from .models import CustomUser
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth import get_user_model
from .utils import normalize_phone_number
from django.contrib.auth.forms import AuthenticationForm

class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(
        label="Email or Phone",
        widget=forms.TextInput(attrs={'autofocus': True}),
        help_text="Enter your email or phone number).",
    )

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=False, help_text="Optional. Enter a valid email address.")
    contact_number = forms.CharField(required=False, help_text="Optional. Enter a valid phone number.")

    class Meta:
        model = CustomUser
        fields = ['email', 'contact_number', 'password1', 'password2']

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        contact_number = cleaned_data.get('contact_number')

        # Ensure at least one of email or contact_number is provided
        if not email and not contact_number:
            raise forms.ValidationError("Either email or contact number must be provided.")

        # Normalize phone number
        if contact_number:
            cleaned_data['contact_number'] = normalize_phone_number(contact_number)

        return cleaned_data


class CustomUserChangeForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('first_name', 'last_name', 'other_name','email','contact_number', 'address', 'date_of_birth','image')


class CustomPasswordResetForm(forms.Form):
    new_password1 = forms.CharField(label='New Password', widget=forms.PasswordInput)
    new_password2 = forms.CharField(label='Confirm New Password', widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        new_password1 = cleaned_data.get('new_password1')
        new_password2 = cleaned_data.get('new_password2')

        if new_password1 and new_password2 and new_password1 != new_password2:
            raise forms.ValidationError("New passwords do not match.")

accounts/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.db.models import Q
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.views.generic import ListView, DetailView, UpdateView
from django.views.generic.edit import CreateView
from .forms import CustomAuthenticationForm
from .forms import CustomUserChangeForm, CustomUserCreationForm, CustomPasswordResetForm
from .models import CustomUser
from .utils import normalize_phone_number
from django.contrib.sessions.models import Session


User = get_user_model()


@login_required
def logout_view(request):
    logout(request)
    return redirect('login')


class UserRegistrationView(CreateView):
    model = CustomUser
    form_class = CustomUserCreationForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('login')  # Redirect to login page after registration


class CustomLoginView(LoginView):
    authentication_form = CustomAuthenticationForm
    template_name = 'login/login.html'

    def form_valid(self, form):
        # Normalize the username (phone number) before authenticating
        username = form.cleaned_data.get('username')
        normalized_username = normalize_phone_number(username)
        form.cleaned_data['username'] = normalized_username
        return super().form_valid(form)


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        if u_form.is_valid():
            u_form.save()
            messages.success(request, f'Your Profile has been updated and Logged!')
            return redirect('profile')
    else:
        u_form = CustomUserChangeForm(instance=request.user)

    context = {
        'u_form': u_form,
    }

    return render(request, 'accounts/users_profile.html', context)


class UserListView(LoginRequiredMixin, ListView):
    model = CustomUser
    template_name = 'accounts/users_list.html'
    context_object_name = 'users'
    paginate_by = 50

    def get_queryset(self):
        query = self.request.GET.get('q')

        if query:
            return CustomUser.objects.filter(
                Q(email__icontains=query) |
                Q(contact_number__icontains=query) |
                Q(first_name__icontains=query) |
                Q(last_name__icontains=query) |
                Q(username__icontains=query)
            )

        return super().get_queryset()


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = CustomUser
    template_name = 'accounts/users_update.html'
    fields = ['first_name', 'last_name', 'email', 'contact_number', 'address', 'date_of_birth',
              'update_comments', 'image']

    def get_queryset(self):
        queryset = super().get_queryset()
        # Filter the queryset to only include the current user
        return queryset.filter(pk=self.kwargs['pk'])

    def get_initial(self):
        initial = super().get_initial()
        initial['update_comments'] = ''  # Set the update_comments field to an empty value
        return initial

    def form_valid(self, form):
        form.instance.updated_date = timezone.now()
        form.instance.updated_by = self.request.user.username

        update_comments = form.cleaned_data['update_comments']
        if not update_comments:
            form.add_error('update_comments', 'Update comments are required.')
            return self.form_invalid(form)

        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, 'User Updated Successfully and Logged.')
        return reverse('user_detail', kwargs={'pk': self.object.pk})


class UserDetailView(LoginRequiredMixin, DetailView):
    model = CustomUser
    template_name = 'accounts/users_details.html'
    context_object_name = 'user'


class UserCreateView(LoginRequiredMixin, CreateView):
    model = CustomUser
    template_name = 'accounts/users_register.html'
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('user_list')

    def form_valid(self, form):
        # Save the user without committing to the database
        user = form.save(commit=False)
        # Set the password manually
        password = form.cleaned_data['password2']
        user.set_password(password)
        # Save the user to the database
        user.save()
        return super().form_valid(form)


@login_required
def reset_password(request, user_id):
    user = User.objects.get(id=user_id)

    if request.method == 'POST':
        form = CustomPasswordResetForm(request.POST)
        if form.is_valid():
            new_password = form.cleaned_data['new_password1']
            user.set_password(new_password)
            # Update admin_password_reset field with username and timestamp
            user.admin_password_reset = f'{request.user.username} ({timezone.now()})'
            user.save()
            messages.success(request, 'Password Changed Successfully and Logged')
            return redirect('user_detail', pk=user.id)
        else:
            messages.error(request, 'Passwords do not match')

    else:
        form = CustomPasswordResetForm()

    return render(request, 'accounts/users_admin_preset.html', {'form': form, 'user': user})


def confirm_logout(request):
    print("Entered confirm_logout view")

    if request.method == 'POST':
        action = request.POST.get('action')

        if action == 'disconnect':
            # Disconnect the previous session
            pending_session_key = request.session.get('pending_session_key')
            if pending_session_key:
                try:
                    Session.objects.get(session_key=pending_session_key).delete()
                    messages.success(request, "Previous session disconnected.")
                except Session.DoesNotExist:
                    messages.warning(request, "Previous session was already inactive.")
        else:
            # Cancel the new login attempt
            request.session.flush()  # Log the user out of the current session
            messages.info(request, "You have kept the other session active.")
            return redirect('login')  # Redirect to the login page

        # Clear pending session data
        request.session.pop('pending_session_key', None)
        request.session.pop('new_session_key', None)

        return redirect('home')  # Redirect to home page after handling

    return render(request, 'login/confirm_logout.html')

accounts/templates/accounts/cp_users_profile.html
{% extends "tra_theme/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Home - Transport Ratings{% endblock %}

{% block content %}

<div class="row">
                    <div class="col-lg-12">
                        <div class="profile">
                            <div class="profile-head">
                                <div class="photo-content">
                                    <div class="cover-photo"></div>
                                    <div class="profile-photo">
                                        <img src="{{ user.image.url}}" class="img-fluid rounded-circle" alt="">
                                    </div>
                                </div>
                                <div class="profile-info">
                                    <div class="row justify-content-center">
                                        <div class="col-xl-8">
                                            <div class="row">
                                                <div class="col-xl-4 col-sm-4 border-right-1 prf-col">
                                                    <div class="profile-name">
                                                        <h4 class="text-primary">{{ user.first_name }} {{ user.last_name }}</h4>
                                                        <p>{{ user.designation }} | {{ user.department }}- {{ user.contact_number }}</p>
                                                    </div>
                                                </div>
                                                <div class="col-xl-4 col-sm-4 border-right-1 prf-col">
                                                    <div class="profile-email">
                                                        <h4 class="text-muted">{{ user.email }}</h4>
                                                        <p>Email</p>
                                                    </div>
                                                </div>
                                                <!-- <div class="col-xl-4 col-sm-4 prf-col">
                                                    <div class="profile-call">
                                                        <h4 class="text-muted">(+1) 321-837-1030</h4>
                                                        <p>Phone No.</p>
                                                    </div>
                                                </div> -->
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

        <!-- [ Main Content ] start -->
        <div class="row">
            <!-- [ sample-page ] start -->
            <div class="col-sm-12">
                <div class="card">

                    <div class="card-header">
                        <div class="card-header-right">
                            <div class="btn-group card-option">
                                <button aria-expanded="false" aria-haspopup="true" class="btn dropdown-toggle btn-icon"
                                        data-bs-toggle="dropdown" type="button">
                                    <i class="feather icon-more-horizontal"></i>
                                </button>
                                <ul class="list-unstyled card-option dropdown-menu dropdown-menu-end">
                                    <li class="dropdown-item full-card"><a href="#"><span><i
                                            class="feather icon-maximize"></i> maximize</span><span
                                            style="display:none"><i
                                            class="feather icon-minimize"></i> Restore</span></a></li>
                                    <li class="dropdown-item minimize-card"><a href="#"><span><i
                                            class="feather icon-minus"></i> collapse</span><span style="display:none"><i
                                            class="feather icon-plus"></i> expand</span></a></li>
                                    <li class="dropdown-item reload-card"><a href="#"><i
                                            class="feather icon-refresh-cw"></i> reload</a></li>
                                    <li class="dropdown-item close-card"><a href="#"><i class="feather icon-trash"></i>
                                        remove</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="content-section">
                            <div class="media">
                                <img class="rounded-circle account-img" src="{{ user.profile.image.url}}">
                                <div class="media-body">
                                    Username: <h2 class="account-heading">{{ user.username }}</h2>
                                    Names: <p class="text-secondary">{{ user.first_name }} {{ user.last_name }}</p>
                                    Email: <p class="text-secondary">{{ user.email }}</p>
                                </div>
                            </div>
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <fieldset class="form-group">
                                    <legend class="border-bottom mb-4">Profile Info</legend>
                                    {{ u_form|crispy }}
                                </fieldset>
                                <div class="form-group">
                                    <a href="/" name="cancel" class="btn btn-warning">Cancel</a>
                                    <button class="btn btn-primary" type="submit">Update My Profile</button>
                                    <a href="{% url 'user_reset_password' %}" name="cancel" class="btn btn-outline-danger">Password Reset</a>


                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- [ sample-page ] end -->
        </div>
        <!-- [ Main Content ] end -->
    </div>
</div>

{% endblock %}

accounts/templates/accounts/logout.html
{% extends "tra_theme/base.html" %}
{% load crispy_forms_tags %}
{% block title %}Search Motor Rating{% endblock %}
{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form|crispy}}
    <button type="submit">Login</button>
</form>
<a href="#">Forgot my Password</a>
<b>You have successfully logged out</b>

<!-- Social login -->
<a href="#">Login with Google</a>
<a href="#">Login with Facebook</a>
{% endblock %}

accounts/templates/accounts/password_reset.html
{% extends "tra_theme/base.html" %}
{% block title %}Password Reset{% endblock %}
{% block content %}
    <!-- Add Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">

<div class="h-100 bg-light d-flex flex-column justify-content-center align-items-center">

    <div class="auth-form bg-white shadow-sm rounded p-4 w-100" style="max-width: 400px;">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>{{ message }}</strong>
            <button aria-label="Close" class="btn-close" data-bs-dismiss="alert" type="button"></button>
        </div>
        {% endfor %}
        {% endif %}

        <h4 class="text-center mb-4 text-success">Transport Sanity</h4>
        <p class="text-center text-muted">Reset your password using your email or phone number.</p>

        {% load crispy_forms_tags %}
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                {{ form|crispy }}
            </fieldset>
            <div class="d-flex justify-content-between">
                <button class="btn btn-success w-100 me-2" type="submit">Request Password Reset</button>
                <button class="btn btn-outline-secondary w-100 ms-2" type="reset">Reset</button>
            </div>
        </form>

        <hr class="my-4">

        <div class="text-center">
            <p class="text-muted">Or reset your password using your phone number</p>
            <a class="btn btn-primary w-100" href="{% url 'send_otp' %}">Reset Using Phone</a>
        </div>

        <hr class="my-4">

        <div class="text-center">
            <a href="{% url 'login' %}" class="btn btn-link text-decoration-none">Back to Login</a>
        </div>
    </div>

    <!-- Add Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends "tra_theme/base.html" %}
{% block title %}Transport Rating{% endblock %}
{% block content %}


<!-- [ auth-signin ] start -->
<div class="auth-wrapper">
    <div class="auth-content">
        <div class="card">
            <div class="row align-items-center text-center">
                <div class="col-md-12">
                    <div class="content-section">
                        <div class="content-section">
                            <div class="alert alert-info">
                                Your password has been reset

                            </div>
                            <a href="{%url 'login' %}">Sign in Here</a>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- [ auth-signin ] end -->

    {% endblock content %}

accounts/templates/accounts/password_reset_confirm.html
{% extends "tra_theme/base.html" %}
{% block title %}Search Motor Rating{% endblock %}
{% load crispy_forms_tags %}

{% block content %}

	<!-- [ auth-signin ] start -->
	<div class="auth-wrapper">
		<div class="auth-content">
			<div class="card">
				<div class="row align-items-center text-center">
					<div class="col-md-12">
						<div class="content-section">
    <div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Reset Your  Password</legend>
            {{form|crispy}}
        </fieldset>
        <div class="form-group">
            <button class="btn-outline-info" type="submit">Reset Password</button>

        </div>
    </form>

</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- [ auth-signin ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

accounts/templates/accounts/password_reset_done.html
{% extends "tra_theme/base.html" %}
{% block title %}Transport Sanity{% endblock %}
{% block content %}

<h4 class="text-center mb-4">Password Reset for account</h4>


<div class="alert alert-info">
    An email has been sent to your EMail with instructions on
    how to reset you password.
</div>
{% endblock content %}

accounts/templates/accounts/user_profile_preset.html
{% extends "tra_theme/base.html" %}
{% load crispy_forms_tags %}
{% block title %}Home - Transport Ratings{% endblock %}
{% block content %}
    <form class="form" method="post">
        {% csrf_token %}
        <p>
            <label for="id_new_password1">New Password:</label>
            {{ form.new_password1 }}
            {% if form.new_password1.errors %}
                <span class="error">{{ form.new_password1.errors }}</span>
            {% endif %}
        </p>
        <p>
            <label for="id_new_password2">Confirm New Password:</label>
            {{ form.new_password2 }}
            {% if form.new_password2.errors %}
                <span class="error">{{ form.new_password2.errors }}</span>
            {% endif %}
        </p>
        <a class="btn btn-warning" href="{% url 'profile' %}">Cancel</a>
        <button class="btn btn-success" type="submit">Reset Password</button>

    </form>



{% endblock content %}

accounts/templates/accounts/users_admin_preset.html
{% extends "tra_theme/base.html" %}
{% load crispy_forms_tags %}
{% block title %}Home - Transport Ratings{% endblock %}
{% block content %}
    <form class="form" method="post">
        {% csrf_token %}
        <p>
            <label for="id_new_password1">New Password:</label>
            {{ form.new_password1 }}
            {% if form.new_password1.errors %}
                <span class="error">{{ form.new_password1.errors }}</span>
            {% endif %}
        </p>
        <p>
            <label for="id_new_password2">Confirm New Password:</label>
            {{ form.new_password2 }}
            {% if form.new_password2.errors %}
                <span class="error">{{ form.new_password2.errors }}</span>
            {% endif %}
        </p>
        <a class="btn btn-warning" href="{% url 'user_detail' user.id %}">Cancel</a>
        <button class="btn btn-success" type="submit">Reset Password</button>

    </form>



{% endblock content %}

accounts/templates/accounts/users_confirm_delete.html
{% extends "tra_theme/base.html" %}
{% load crispy_forms_tags %}
{% block title %}Home - Transport Ratings{% endblock %}
{% block content %}
<!-- [ Main Content ] start -->
<div class="pcoded-main-container">
    <div class="pcoded-content">
        <!-- [ breadcrumb ] start -->
        <div class="page-header">
            <div class="page-block">
                <div class="row align-items-center">
                    <div class="col-md-12">
                        <div class="page-header-title">
                            <h5 class="m-b-10">Manage Users</h5>
                        </div>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="/"><i class="feather icon-home"></i></a></li>
                            <li class="breadcrumb-item"><a href="#">Manage Users</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- [ breadcrumb ] end -->
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>{{message}}</strong>
            <button aria-label="Close" class="close" data-dismiss="alert" type="button"><span
                    aria-hidden="true">×</span></button>
        </div>

        {% endfor %}
        {% endif %}
        <!-- [ Main Content ] start -->
        <div class="row">
            <!-- [ sample-page ] start -->
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h5>List of Users</h5>
                        <div class="card-header-right">
                            <div class="btn-group card-option">
                                <button aria-expanded="false" aria-haspopup="true" class="btn dropdown-toggle btn-icon"
                                        data-bs-toggle="dropdown" type="button">
                                    <i class="feather icon-more-horizontal"></i>
                                </button>
                                <ul class="list-unstyled card-option dropdown-menu dropdown-menu-end">
                                    <li class="dropdown-item full-card"><a href="#"><span><i
                                            class="feather icon-maximize"></i> maximize</span><span
                                            style="display:none"><i
                                            class="feather icon-minimize"></i> Restore</span></a></li>
                                    <li class="dropdown-item minimize-card"><a href="#"><span><i
                                            class="feather icon-minus"></i> collapse</span><span style="display:none"><i
                                            class="feather icon-plus"></i> expand</span></a></li>
                                    <li class="dropdown-item reload-card"><a href="#"><i
                                            class="feather icon-refresh-cw"></i> reload</a></li>
                                    <li class="dropdown-item close-card"><a href="#"><i class="feather icon-trash"></i>
                                        remove</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <h1>Confirm Delete</h1>

                        <p>Are you sure you want to delete user "{{ user.first_name }} {{ user.last_name }}"?</p>

                        <form method="POST">
                            {% csrf_token %}
                            <button type="submit">Delete</button>
                            <a href="{% url 'user_list' %}">Cancel</a>
                        </form>

                    </div>
                </div>
            </div>
            <!-- [ sample-page ] end -->
        </div>
        <!-- [ Main Content ] end -->
    </div>
</div>
<!-- [ Main Content ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

accounts/templates/accounts/users_register.html
{% extends "tra_theme/base.html" %}
{% load crispy_forms_tags %}
{% block title %}Home - Transport Ratings{% endblock %}
{% block content %}
<!-- user_create.html -->
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form|crispy}}
  <a href="{% url 'user_list' %}" class="btn btn-warning"> Cancel</a>
  <button class="btn btn-success" type="submit">Create User</button>
</form>

{% endblock content %}